# - name: Ensure bin directory
#   file:
#     path: /home/oliver/bin
#     state: directory
#     owner: oliver
#     group: oliver
#     mode: '0700'
# - name: Download BitWarden
#   get_url:
#       url: https://vault.bitwarden.com/download/?app=desktop&platform=linux
#       dest: /home/oliver/bin/BitWarden.AppImage
#       owner: oliver
#       group: oliver
#       mode: '0700'
- name: Install BitWarden flatpak
  shell: flatpak install flathub com.bitwarden.desktop
