- name: Download ProtonVPN Repo Package
  get_url:
      url: https://protonvpn.com/download/protonvpn-stable-release_1.0.0-1_all.deb
      dest: /home/{{ ansible_env.USER }}/bin/
      owner: {{ ansible_env.USER }}
      group: {{ ansible_env.USER }}
      mode: '0700'
- name: Install ProtonVPN Repo Package
  apt:
    deb: /home/{{ ansible_env.USER }}/protonvpn-stable-release_1.0.0-1_all.deb
- name: Install ProtonVPN
  apt:
    update_cache: yes
    name: protonvpn
