- name: Check ProtonVPN Install Status
  package_facts:
    manager: auto
- name: Download ProtonVPN Repo Package
  get_url:
      url: https://protonvpn.com/download/protonvpn-stable-release_1.0.0-1_all.deb
      dest: /home/oliver/bin/
      owner: oliver
      group: oliver
      mode: '0700'
  when: '"protonvpn" not in ansible_facts.packages'
- name: Install ProtonVPN Repo Package
  apt:
    deb: /home/{{ ansible_env.USER }}/protonvpn-stable-release_1.0.0-1_all.deb
  when: '"protonvpn" not in ansible_facts.packages'
- name: Install ProtonVPN
  apt:
    update_cache: yes
    name: protonvpn
  when: '"protonvpn" not in ansible_facts.packages'
